publish_mode: editorial_workflow
media_folder: "/static/images/blog"
public_folder: "/images/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    extension: "md"
    create: true
    slug: "{{slug}}" # blog filenames, e.g., YYYY-MM-DD-title.md
    path: "{{year}}/{{month}}/{{day}}/{{slug}}" # where the file will be saved on the os filesys
    preview_path: "blog/{{year}}/{{month}}/{{slug}}" # url path where the content will be found
    media_folder: "{{media_folder}}" # must be specified or the blog folder will be used for static
    public_folder: "{{public_folder}}" # same as above
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "coverimg", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" } # body: what comes after frontmatter
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Path", name: "path", widget: "hidden", default: "/" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Path", name: "path", widget: "hidden", default: "/about" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
